import Level1 from './Level1';
import Level2 from './Level2';
import Level3 from './Level3';
import Level4 from './Level4';
import Level5 from './Level5';

export const AllQuestions = [...Level1, ...Level2, ...Level3, ...Level4, ...Level5];
export const QuestionsTitles = [
    ['1', [{name: '1.A.1', type: 'Addition'}, {name: '1.A.2', type: 'Addition'}, {name: '1.A.3', type: 'Addition'}, {name: '1.A.4', type: 'Addition'}, {name: '1.AS.1', type: 'Addition/Subtraction'}, {name: '1.AS.2', type: 'Addition/Subtraction'}, {name: '1.C.1', type: 'Counting'}, {name: '1.C.2', type: 'Counting'}, {name: '1.G.1', type: 'Geometry'}, {name: '1.I.1', type: 'Inequalities'}, {name: '1.I.2', type: 'Inequalities'}, {name: '1.NL.1', type: 'Number Line'}, {name: '1.PS.1', type: 'Problem Solving'}, {name: '1.PV.1', type: 'Place Value'}, {name: '1.S.1', type: 'Subtraction'}, {name: '1.S.2', type: 'Subtraction'}], ['Snapshot','Addition', 'Addition/Subtraction', 'Counting', 'Geometry', 'Inequalities', 'Number Line', 'Problem Solving', 'Place Value', 'Subtraction']],
    ['2', [{name: '2.A.1', type: 'Addition'}, {name: '2.A.2', type: 'Addition'}, {name: '2.A.3', type: 'Addition'}, {name: '2.A.4', type: 'Addition'}, {name: '2.C.1', type: 'Counting'}, {name: '2.F.1', type: 'Fractions'}, {name: '2.I.1', type: 'Inequalities'}, {name: '2.OE.1', type: 'Odd/Even'}, {name: '2.OE.2', type: 'Odd/Even'}, {name: '2.PS.1', type: 'Problem Solving'}, {name: '2.S.1', type: 'Subtraction'}, {name: '2.S.2', type: 'Subtraction'}, {name: '2.S.3', type: 'Subtraction'}, {name: '2.S.4', type: 'Subtraction'}], ['Snapshot','Addition', 'Counting', 'Fractions', 'Inequalities', 'Odd/Even', 'Problem Solving', 'Subtraction']],
    ['3', [{name: '3.A.1', type: 'Addition'}, {name: '3.A.2', type: 'Addition'}, {name: '3.A.3', type: 'Addition'}, {name: '3.A.4', type: 'Addition'}, {name: '3.A.5', type: 'Addition'}, {name: '3.D.1', type: 'Division'}, {name: '3.D.2', type: 'Division'}, {name: '3.E.1', type: 'Estimation'}, {name: '3.E.2', type: 'Estimation'}, {name: '3.F.1', type: 'Fractions'}, {name: '3.F.2', type: 'Fractions'}, {name: '3.F.3', type: 'Fractions'}, {name: '3.G.1', type: 'Geometry'}, {name: '3.G.2', type: 'Geometry'}, {name: '3.G.3', type: 'Geometry'}, {name: '3.G.4', type: 'Geometry'}, {name: '3.G.5', type: 'Geometry'}, {name: '3.G.6', type: 'Geometry'}, {name: '3.M.1', type: 'Multiplication'}, {name: '3.M.2', type: 'Multiplication'}, {name: '3.PS.1', type: 'Problem Solving'}, {name: '3.S.1', type: 'Subtraction'}], ['Snapshot','Addition', 'Division', 'Estimation', 'Fractions', 'Geometry', 'Multiplication', 'Problem Solving', 'Subtraction']],
    ['4', [{name: '4.D.1', type: 'Division'}, {name: '4.D.2', type: 'Division'}, {name: '4.D.3', type: 'Division'}, {name: '4.D.4', type: 'Division'}, {name: '4.D.5', type: 'Division'}, {name: '4.F.1', type: 'Fractions'}, {name: '4.F.2', type: 'Fractions'}, {name: '4.F.3', type: 'Fractions'}, {name: '4.F.4', type: 'Fractions'}, {name: '4.F.5', type: 'Fractions'}, {name: '4.F.6', type: 'Fractions'}, {name: '4.F.7', type: 'Fractions'}, {name: '4.F.8', type: 'Fractions'}, {name: '4.FD.1', type: 'Fractions/Decimals'}, {name: '4.FD.2', type: 'Fractions/Decimals'}, {name: '4.G.1', type: 'Geometry'}, {name: '4.G.2', type: 'Geometry'}, {name: '4.I.1', type: 'Inequalities'}, {name: '4.I.2', type: 'Inequalities'}, {name: '4.LCM.1', type: 'Least Common Multiple'}, {name: '4.M.1', type: 'Multiplication'}, {name: '4.M.2', type: 'Multiplication'}, {name: '4.M.3', type: 'Multiplication'}, {name: '4.M.4', type: 'Multiplication'}, {name: '4.M.5', type: 'Multiplication'}, {name: '4.M.6', type: 'Multiplication'}, {name: '4.M.7', type: 'Multiplication'}, {name: '4.PC.1', type: 'Prime/Composite'}, {name: '4.PV.1', type: 'Place Value'}, {name: '4.R.1', type: 'Rounding'}], ['Snapshot','Division', 'Fractions', 'Fractions/Decimals', 'Geometry', 'Inequalities', 'Least Common Multiple', 'Multiplication', 'Prime/Composite', 'Place Value', 'Rounding']],
    ['5', [{name: '5.A.1', type: 'Addition'}, {name: '5.AS.1', type: 'Addition/Subtraction'}, {name: '5.D.1', type: 'Division'}, {name: '5.D.2', type: 'Division'}, {name: '5.EX.1', type: 'Expressions'}, {name: '5.EX.2', type: 'Expressions'}, {name: '5.EXP.1', type: 'Exponents'}, {name: '5.EXP.2', type: 'Exponents'}, {name: '5.F.1', type: 'Fractions'}, {name: '5.F.2', type: 'Fractions'}, {name: '5.F.3', type: 'Fractions'}, {name: '5.F.4', type: 'Fractions'}, {name: '5.F.5', type: 'Fractions'}, {name: '5.F.6', type: 'Fractions'}, {name: '5.F.7', type: 'Fractions'}, {name: '5.F.8', type: 'Fractions'}, {name: '5.F.9', type: 'Fractions'}, {name: '5.F.10', type: 'Fractions'}, {name: '5.FD.1', type: 'Fractions/Decimals'}, {name: '5.FD.2', type: 'Fractions/Decimals'}, {name: '5.G.1', type: 'Geometry'}, {name: '5.G.2', type: 'Geometry'}, {name: '5.G.3', type: 'Geometry'}, {name: '5.GR.1', type: 'Graphing'}, {name: '5.I.1', type: 'Inequalities'}, {name: '5.I.2', type: 'Inequalities'}, {name: '5.M.1', type: 'Multiplication'}, {name: '5.M.1', type: 'Multiplication'}, {name: '5.PV.1', type: 'Place Value'}, {name: '5.R.1', type: 'Rounding'}, {name: '5.S.1', type: 'Subtraction'}, {name: '5.T.1', type: 'Time'}], ['Snapshot','Addition', 'Addition/Subtraction', 'Division', 'Expressions', 'Exponents', 'Fractions', 'Fractions/Decimals', 'Geometry', 'Graphing', 'Inequalities', 'Multiplication', 'Place Value', 'Rounding', 'Subtraction', 'Time']]
]